<a href="https://colab.research.google.com/github/shivakr07/Machine-Learning/blob/main/NN_Training_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-1.22339339, -0.53057319, -1.20132178, ..., -0.92936074,
        -0.58598343,  0.03647992],
       [-0.34134597, -0.68463688, -0.38462854, ..., -0.4860377 ,
         0.1989667 , -0.79703248],
       [-1.30025229, -1.59267894, -1.28939254, ..., -0.79289487,
        -0.71867357, -0.34488355],
       ...,
       [ 0.71159285,  0.49418379,  0.73541955, ...,  1.4570345 ,
         1.14058713,  0.6378819 ],
       [ 0.24706102, -0.87604935,  0.22371211, ...,  0.3628625 ,
         0.08705935, -0.02168487],
       [-0.15834858, -1.25187138, -0.13754112, ..., -0.35537889,
         0.26451244, -0.12319889]])

In [9]:
y_train

110    B
195    B
21     B
413    B
55     B
      ..
297    M
187    B
24     M
227    B
221    B
Name: diagnosis, Length: 455, dtype: object

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0])

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor.shape

torch.Size([455, 30])

In [14]:
y_train_tensor.shape

torch.Size([455])

In [15]:
# Now we have all the data in required format
# Now we will define our model
# we have 30 features [cols] so here we will take 30 weights an 1 bias [here we have simple neuron or 1 neuron]

In [38]:
class NNet():
  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    # here X.shape[1] will give 30 so it will be a 30*1 metrices
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)
    # since we have one neuron so only 1 bias is required

  # define forward pass
  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    ypred = torch.sigmoid(z)
    return ypred

  # define loss function [since this is binary classification so we will use binary cross entropy]
  def loss_fun(self, ypred, y):
    # Clamp predictions to avoid the log(0)
    epsilon = 1e-7
    ypred = torch.clamp(ypred, epsilon, 1-epsilon)

    # calculate loss
    loss = -(y_train_tensor*torch.log(ypred) + (1 + y_train_tensor) * torch.log(1 - ypred)).mean()
    return loss

In [43]:
learning_rate = 0.1
epochs = 25

In [44]:
# define the model
model = NNet(X_train_tensor)
model.weights

tensor([[0.6812],
        [0.0358],
        [0.2174],
        [0.4001],
        [0.8093],
        [0.0583],
        [0.4407],
        [0.3250],
        [0.2058],
        [0.0572],
        [0.7006],
        [0.0924],
        [0.3687],
        [0.5890],
        [0.6943],
        [0.0066],
        [0.7229],
        [0.1325],
        [0.5047],
        [0.6944],
        [0.1254],
        [0.5349],
        [0.5939],
        [0.2576],
        [0.5554],
        [0.8297],
        [0.1796],
        [0.1840],
        [0.3931],
        [0.5535]], dtype=torch.float64, requires_grad=True)

In [35]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [47]:
# model training

for epoch in range(epochs):
  # forward pass
  ypred = model.forward(X_train_tensor)
  # print(ypred)

  # calculate loss
  loss =  model.loss_fun(ypred, y_train_tensor)
  # print(f'Epoch : {epoch + 1}, Loss : {loss.item()}')
  # backward pass
  # parameters update

  # backword pass
  loss.backward()

  # weights update
  # here we don't need gradient tracking
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # make gradients 0 to avoid the accumulation
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f'Epoch : {epoch + 1}, Loss : {loss.item()}')

Epoch : 1, Loss : 1.012678390869818
Epoch : 2, Loss : 1.006368067712158
Epoch : 3, Loss : 1.0005849040812187
Epoch : 4, Loss : 0.9952768583372738
Epoch : 5, Loss : 0.9903979065720669
Epoch : 6, Loss : 0.9859071596234144
Epoch : 7, Loss : 0.9817681684747434
Epoch : 8, Loss : 0.9779483610903036
Epoch : 9, Loss : 0.9744185738781982
Epoch : 10, Loss : 0.9711526538547852
Epoch : 11, Loss : 0.9681271157243618
Epoch : 12, Loss : 0.9653208431868386
Epoch : 13, Loss : 0.9627148269667899
Epoch : 14, Loss : 0.9602919340481023
Epoch : 15, Loss : 0.9580367038626352
Epoch : 16, Loss : 0.9559351680076927
Epoch : 17, Loss : 0.9539746906322406
Epoch : 18, Loss : 0.9521438270412885
Epoch : 19, Loss : 0.9504321983834851
Epoch : 20, Loss : 0.9488303805441402
Epoch : 21, Loss : 0.9473298055843196
Epoch : 22, Loss : 0.9459226742573889
Epoch : 23, Loss : 0.9446018783033445
Epoch : 24, Loss : 0.9433609313720167
Epoch : 25, Loss : 0.9421939075608345